# -*- coding: utf-8 -*-
"""PM project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRJJDEtLH-LiRENr5qFVJKivWlViRSZV

## 1. Data Generation & Preprocessing

Division of the data by stages
"""

import pandas as pd
import numpy as np
import random

# --- CONFIGURATION ---
STAGES = ['Site_Prep', 'Foundations', 'Structure', 'Systems', 'Finishing']

UNIT_COST_RANGES = {
    'Building': (2000, 3200), 'Bridge': (4500, 6500), 'Power Plant': (6000, 9000),
    'Water Infra': (1800, 2600), 'Road': (300, 700)
}

RANGES = {
    'Building': {'Time': [(5,10),(10,15),(15,25),(20,30),(25,35)], 'Cost': [(3,7),(10,15),(20,30),(20,35),(15,25)], 'Risk': [(40,50),(80,90),(30,45),(50,65),(20,35)]},
    'Bridge': {'Time': [(5,10),(20,30),(30,40),(10,15),(10,15)], 'Cost': [(5,8),(15,25),(35,45),(10,15),(10,15)], 'Risk': [(35,45),(85,95),(75,85),(30,40),(15,25)]},
    'Power Plant': {'Time': [(10,15),(15,20),(15,20),(30,45),(10,20)], 'Cost': [(5,10),(10,15),(15,20),(45,60),(10,15)], 'Risk': [(50,60),(70,80),(40,50),(85,95),(70,85)]},
    'Water Infra': {'Time': [(15,20),(20,25),(25,35),(15,20),(10,15)], 'Cost': [(10,15),(15,20),(35,45),(15,25),(5,10)], 'Risk': [(75,85),(90,95),(35,50),(50,65),(60,75)]},
    'Road': {'Time': [(30,40),(15,20),(20,25),(10,15),(10,15)], 'Cost': [(20,30),(15,20),(25,30),(10,15),(20,25)], 'Risk': [(85,95),(60,75),(40,50),(25,35),(20,35)]}
}

def get_normalized_values(asset_type, metric, target_total, is_average=False):
    ranges = RANGES[asset_type][metric]
    raw_vals = [random.uniform(low, high) for (low, high) in ranges]
    actual_target_sum = target_total * len(STAGES) if is_average else target_total
    ratio = actual_target_sum / sum(raw_vals)
    return [v * ratio for v in raw_vals]

# --- PROCESSING ---
df_raw = pd.read_csv('Engineering_Cost_Feasibility_Dataset.csv')
planned_list = []

for _, original_row in df_raw.iterrows():
    row = original_row.to_dict()
    p_type = str(row['Project_Type'])

    # 1. ENGINEERED AREA
    min_uc, max_uc = UNIT_COST_RANGES[p_type]
    row['Engineered_Area'] = round(float(row['Estimated_Cost_USD']) / random.uniform(min_uc, max_uc), 2)

    # 2. BASES FOR BREAKDOWN
    p_costs = get_normalized_values(p_type, 'Cost', float(row['Estimated_Cost_USD']))
    p_days = get_normalized_values(p_type, 'Time', float(row['Time_Estimate_Days']))
    s_risks = get_normalized_values(p_type, 'Risk', float(row['Risk_Assessment_Score']), is_average=True)

    for i, stage in enumerate(STAGES):
        row[f'{stage}_Planned_Cost'] = round(p_costs[i], 2)
        row[f'{stage}_Planned_Days'] = int(round(p_days[i]))
        row[f'{stage}_Stage_Risk'] = round(min(s_risks[i], 100), 2)

    planned_list.append(row)

df_planned = pd.DataFrame(planned_list)
df_planned.to_csv('1_Data_by_stages.csv', index=False)
print("Part 1 Success: 'Planned_Breakdown.csv' created.")

"""Calculation of the actual cost and time"""

import pandas as pd

# --- CONFIGURATION ---
STAGES = ['Site_Prep', 'Foundations', 'Structure', 'Systems', 'Finishing']

# Updated internal weights for 3 levels (Simulation logic)
# High has a stronger impact since 'Extreme' was removed
COMPLEXITY_WEIGHTS = {
    'Low': 0.2,
    'Medium': 0.6,
    'High': 1.1
}

def map_complexity_label(score):
    """Maps the numeric score 1, 2, 3 to specific labels."""
    # We use 1.5 and 2.5 as midpoints to handle any floating point noise
    if score < 1.5:
        return 'Low'
    elif score < 2.5:
        return 'Medium'
    else:
        return 'High'

# --- PROCESSING ---
# Load the output from Part 1
df_planned = pd.read_csv('1_Data_by_stages.csv')
final_list = []

print("Simulating execution with 3-level Complexity (Low, Medium, High)...")

for _, original_row in df_planned.iterrows():
    row = original_row.to_dict()

    # 1. Define Complexity Category and Factor
    comp_score = float(row['Scope_Complexity_Numeric'])
    comp_label = map_complexity_label(comp_score)
    comp_factor = COMPLEXITY_WEIGHTS[comp_label]

    hist_dev = float(row['Historical_Cost_Deviation_%']) / 100
    resources = float(row.get('Resources', 5))

    actual_cost_total = 0
    actual_time_total = 0

    # 2. CALCULATE ACTUALS PER STAGE
    for stage in STAGES:
        p_cost = row[f'{stage}_Planned_Cost']
        p_days = row[f'{stage}_Planned_Days']
        s_risk = row[f'{stage}_Stage_Risk']

        # Cost Actual Formula: Impact of Area, Risk, and Complexity Factor
        # Note: Engineered_Area is used here as a slight overhead multiplier
        area_multiplier = 1 + (row['Engineered_Area'] / 1000000) # Minor scale impact
        cost_variance = (1 + hist_dev) * (1 + (comp_factor * 0.05)) * (1 + (s_risk / 1000)) * area_multiplier
        res_efficiency = 1 - (resources * 0.01)

        a_cost = round(p_cost * cost_variance * res_efficiency, 2)

        # Time Actual Formula
        time_variance = (1 + (s_risk / 150)) * (1 + (comp_factor * 0.08))
        res_delay = 1.3 - (resources / 10)
        a_days = int(round(p_days * time_variance * res_delay))

        row[f'{stage}_Actual_Cost'] = a_cost
        row[f'{stage}_Actual_Days'] = a_days

        actual_cost_total += a_cost
        actual_time_total += a_days

    # 3. ASSIGN TOTALS AND LABEL
    row['Actual_Cost_Total'] = round(actual_cost_total, 2)
    row['Actual_Time_Total'] = actual_time_total
    row['Complexity_Level'] = comp_label

    final_list.append(row)

# --- FINAL TRANSFORMATION & ONE-HOT ---
df_final = pd.DataFrame(final_list)

# Perform One-Hot Encoding for the 3 levels
# This creates Comp_Low, Comp_Medium, Comp_High
df_final = pd.get_dummies(df_final, columns=['Complexity_Level'], prefix='Comp')

# Remove the numeric complexity column to finalize the categorical approach
if 'Scope_Complexity_Numeric' in df_final.columns:
    df_final.drop(columns=['Scope_Complexity_Numeric'], inplace=True)

# Save result
df_final.to_csv('2_Data_actual_cost_time.csv', index=False)

print(f"Success! {len(df_final)} rows processed.")
print("One-Hot columns created: ", [col for col in df_final.columns if col.startswith('Comp_')])

"""Augmentation 21k samples"""

import pandas as pd
import numpy as np

# Configuration
TARGET_ROWS = 21000
df = pd.read_csv('2_Data_actual_cost_time.csv')
project_col = 'Project_Type'

# --- FIX 1: UPDATE COLUMN CATEGORIZATION ---
# 'Scope_Complexity_Numeric' is removed because it no longer exists in your CSV
discrete_cols = []
percentage_cols = ['Risk_Assessment_Score', 'Resource_Allocation_Score']
linear_cols = ['Engineered_Area', 'Actual_Cost_Total', 'Actual_Time_Total', 'Time_Estimate_Days']

# Automatically identify all other columns (categorical/one-hot dummies)
all_cols = df.columns.tolist()
processed_cols = [project_col] + discrete_cols + percentage_cols + linear_cols
# This list now correctly includes 'Comp_Low', 'Comp_Medium', 'Comp_High'
remaining_cols = [c for c in all_cols if c not in processed_cols]

# 1. Maintain Original Class Distribution
weights = df[project_col].value_counts(normalize=True)
needed_count = TARGET_ROWS - len(df)
synthetic_data = []

print(f"Starting augmentation. Generating {needed_count} new rows...")

for i in range(needed_count):
    p_type = np.random.choice(weights.index, p=weights.values)
    subset = df[df[project_col] == p_type]

    # Select parents
    idx = subset.index
    row1, row2 = subset.loc[np.random.choice(idx)], subset.loc[np.random.choice(idx)]

    # Interpolation factor
    alpha = np.random.uniform(-0.05, 1.05)
    new_row = {project_col: p_type}

    # 2. Process Numeric Columns
    for col in linear_cols + percentage_cols + discrete_cols:
        val = (row1[col] * alpha) + (row2[col] * (1 - alpha))

        if col in percentage_cols:
            noise = np.random.normal(0, 2.0)
            new_row[col] = np.clip(val + noise, 0, 100)
        else:
            # Add small noise to linear values
            noise_level = 0.02 if i % 10 != 0 else 0.05
            noise = np.random.normal(0, abs(noise_level * val))
            new_row[col] = val + noise

    # 3. Process Remaining Columns (One-Hot Dummies & Categorical)
    # We pick from ONE parent to ensure categorical integrity
    # (Fixes the ValueError: a must be 1-dimensional)
    if np.random.rand() < 0.5:
        chosen_parent = row1
    else:
        chosen_parent = row2

    for col in remaining_cols:
        new_row[col] = chosen_parent[col]

    synthetic_data.append(new_row)

# 4. Final Assembly
df_synthetic = pd.DataFrame(synthetic_data)
df_final = pd.concat([df, df_synthetic], ignore_index=True)

# Ensure physical constraints
for col in ['Engineered_Area', 'Actual_Cost_Total']:
    if col in df_final.columns:
        df_final[col] = df_final[col].clip(lower=df[col].min() * 0.8)

# Verification
print(f"Augmentation complete. Total rows: {len(df_final)}")
print(f"Final column count: {len(df_final.columns)}")
print(f"Missing values check: {df_final.isnull().sum().sum()}")

df_final.to_csv('3_Data_21ksamples.csv', index=False)

display(df_final.describe())

"""# Visualization

Visualization of original samples
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Load your processed data
df = pd.read_csv('2_Data_actual_cost_time.csv')

# --- 2. RECONSTRUCT CATEGORICAL COMPLEXITY FOR VISUALIZATION ---
# This creates a single column where Low=1, Medium=2, High=3 for the plot
def get_complexity_rank(row):
    if row.get('Comp_Low') == 1: return 1
    if row.get('Comp_Medium') == 1: return 2
    if row.get('Comp_High') == 1: return 3
    return 0

df['Complexity_Plot_Axis'] = df.apply(get_complexity_rank, axis=1)

# 3. Define Parameters
# We use the reconstructed 'Complexity_Plot_Axis' instead of individual dummies
param_cols = [
    'Engineered_Area',
    'Complexity_Plot_Axis', # Combined axis
    'Risk_Assessment_Score',
    'Resource_Allocation_Score',
    'Time_Estimate_Days'
]

output_cols = [
    'Actual_Cost_Total',
    'Actual_Time_Total'
]

# Labels to match
label_params = ['Engineered Area', 'Complexity (Low->High)', 'Risk Score', 'Resource Score', 'Estimated Days']
label_output = ['Total Actual Cost ($)', 'Total Actual Time (Days)']

# --- Setup Categorical Colors ---
project_types = df['Project_Type'].unique()
colors = plt.get_cmap('tab10', len(project_types))
type_color_map = {ptype: colors(i) for i, ptype in enumerate(project_types)}

# 4. Setup Plotting Variables
num_samples = len(df)
num_params = len(param_cols)
num_output = len(output_cols)

sample_size = min(3000, num_samples)
df_subset = df.sample(n=sample_size, random_state=42)

# 5. Create the Visualization
fig, axs = plt.subplots(num_output, num_params, figsize=(20, 10),
                        sharex=False, sharey='row', squeeze=False)

for o in range(num_output):
    for p in range(num_params):
        for ptype in project_types:
            group = df_subset[df_subset['Project_Type'] == ptype]

            # Add a small 'jitter' to the Complexity axis so dots don't overlap perfectly
            x_data = group[param_cols[p]]
            if param_cols[p] == 'Complexity_Plot_Axis':
                x_data = x_data + np.random.uniform(-0.15, 0.15, size=len(x_data))

            axs[o, p].scatter(
                x_data,
                group[output_cols[o]],
                s=10,
                alpha=0.5,
                label=ptype,
                color=type_color_map[ptype]
            )

        axs[o, p].grid(True, linestyle=':', alpha=0.6)

        # Customizing the Complexity Axis ticks
        if param_cols[p] == 'Complexity_Plot_Axis':
            axs[o, p].set_xticks([1, 2, 3])
            axs[o, p].set_xticklabels(['Low', 'Med', 'High'])

        # Labeling
        if o == num_output - 1:
            axs[o, p].set_xlabel(label_params[p], fontweight='bold')
        if p == 0:
            axs[o, p].set_ylabel(label_output[o], fontweight='bold')

# 6. Legend and Formatting
handles, labels = axs[0, 0].get_legend_handles_labels()
fig.legend(handles, labels, loc='upper right', title='Project Types', fontsize=10, bbox_to_anchor=(0.98, 0.95))

plt.tight_layout()
fig.subplots_adjust(top=0.90, right=0.88)
fig.suptitle('Numerical & Categorical Impact Analysis', fontsize=20, fontweight='bold')

plt.show()

"""Visualization of 21 000 samples"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Load your processed data
df = pd.read_csv('3_Data_21ksamples.csv')

# --- 2. RECONSTRUCT CATEGORICAL COMPLEXITY FOR VISUALIZATION ---
# This creates a single column where Low=1, Medium=2, High=3 for the plot
def get_complexity_rank(row):
    if row.get('Comp_Low') == 1: return 1
    if row.get('Comp_Medium') == 1: return 2
    if row.get('Comp_High') == 1: return 3
    return 0

df['Complexity_Plot_Axis'] = df.apply(get_complexity_rank, axis=1)

# 3. Define Parameters
# We use the reconstructed 'Complexity_Plot_Axis' instead of individual dummies
param_cols = [
    'Engineered_Area',
    'Complexity_Plot_Axis', # Combined axis
    'Risk_Assessment_Score',
    'Resource_Allocation_Score',
    'Time_Estimate_Days'
]

output_cols = [
    'Actual_Cost_Total',
    'Actual_Time_Total'
]

# Labels to match
label_params = ['Engineered Area', 'Complexity (Low->High)', 'Risk Score', 'Resource Score', 'Estimated Days']
label_output = ['Total Actual Cost ($)', 'Total Actual Time (Days)']

# --- Setup Categorical Colors ---
project_types = df['Project_Type'].unique()
colors = plt.get_cmap('tab10', len(project_types))
type_color_map = {ptype: colors(i) for i, ptype in enumerate(project_types)}

# 4. Setup Plotting Variables
num_samples = len(df)
num_params = len(param_cols)
num_output = len(output_cols)

sample_size = min(3000, num_samples)
df_subset = df.sample(n=sample_size, random_state=42)

# 5. Create the Visualization
fig, axs = plt.subplots(num_output, num_params, figsize=(20, 10),
                        sharex=False, sharey='row', squeeze=False)

for o in range(num_output):
    for p in range(num_params):
        for ptype in project_types:
            group = df_subset[df_subset['Project_Type'] == ptype]

            # Add a small 'jitter' to the Complexity axis so dots don't overlap perfectly
            x_data = group[param_cols[p]]
            if param_cols[p] == 'Complexity_Plot_Axis':
                x_data = x_data + np.random.uniform(-0.15, 0.15, size=len(x_data))

            axs[o, p].scatter(
                x_data,
                group[output_cols[o]],
                s=10,
                alpha=0.5,
                label=ptype,
                color=type_color_map[ptype]
            )

        axs[o, p].grid(True, linestyle=':', alpha=0.6)

        # Customizing the Complexity Axis ticks
        if param_cols[p] == 'Complexity_Plot_Axis':
            axs[o, p].set_xticks([1, 2, 3])
            axs[o, p].set_xticklabels(['Low', 'Med', 'High'])

        # Labeling
        if o == num_output - 1:
            axs[o, p].set_xlabel(label_params[p], fontweight='bold')
        if p == 0:
            axs[o, p].set_ylabel(label_output[o], fontweight='bold')

# 6. Legend and Formatting
handles, labels = axs[0, 0].get_legend_handles_labels()
fig.legend(handles, labels, loc='upper right', title='Project Types', fontsize=10, bbox_to_anchor=(0.98, 0.95))

plt.tight_layout()
fig.subplots_adjust(top=0.90, right=0.88)
fig.suptitle('Numerical & Categorical Impact Analysis', fontsize=20, fontweight='bold')

plt.show()

"""## 2. Neural network training"""

import jax
import jax.numpy as jnp
import numpy as np
import pandas as pd
import optax
import matplotlib.pyplot as plt
from flax import nnx
import joblib
import time

# --- 1. DATA PREPARATION ---
df = pd.read_csv('3_Data_21ksamples.csv')

cost_stages = ['Site_Prep_Actual_Cost', 'Foundations_Actual_Cost', 'Structure_Actual_Cost', 'Systems_Actual_Cost', 'Finishing_Actual_Cost']
time_stages = ['Site_Prep_Actual_Days', 'Foundations_Actual_Days', 'Structure_Actual_Days', 'Systems_Actual_Days', 'Finishing_Actual_Days']
output_cols = cost_stages + time_stages

# 1.1 Cleaning
cols_to_fix = ['Engineered_Area', 'Estimated_Cost_USD', 'Risk_Assessment_Score',
               'Resource_Allocation_Score', 'Time_Estimate_Days'] + output_cols
for col in cols_to_fix:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df = df.replace([np.inf, -np.inf], np.nan).dropna(subset=cols_to_fix + ['Project_Type', 'Scope_Complexity'])

# --- 1.2 LOGIC INJECTION ---
total_actual = df[cost_stages].sum(axis=1)
df['Historical_Overrun_Ratio'] = total_actual / df['Estimated_Cost_USD']
global_overrun_avg = df['Historical_Overrun_Ratio'].mean()

avg_cost_weights = df[cost_stages].div(df[cost_stages].sum(axis=1), axis=0).mean()
avg_time_weights = df[time_stages].div(df[time_stages].sum(axis=1), axis=0).mean().values.tolist()

type_risk_dist = df.groupby('Project_Type')[cost_stages].mean()
type_risk_dist = type_risk_dist.div(type_risk_dist.sum(axis=1), axis=0)

for i in range(5):
    df[f'Est_Stage_Cost_{i}'] = df['Estimated_Cost_USD'] * avg_cost_weights.iloc[i] * global_overrun_avg
    df[f'Stage_Risk_{i}'] = df.apply(
        lambda row: row['Risk_Assessment_Score'] * type_risk_dist.loc[row['Project_Type']].iloc[i], axis=1
    )

engineered_inputs = [f'Est_Stage_Cost_{i}' for i in range(5)] + [f'Stage_Risk_{i}' for i in range(5)]
continuous_input_cols = ['Engineered_Area', 'Resource_Allocation_Score', 'Time_Estimate_Days'] + engineered_inputs

proj_dummies = pd.get_dummies(df['Project_Type'], prefix='Proj')
comp_dummies = pd.get_dummies(df['Scope_Complexity'], prefix='Comp')

X_raw = pd.concat([proj_dummies, comp_dummies, df[continuous_input_cols]], axis=1).values.astype(np.float32)
Y_raw = df[output_cols].values.astype(np.float32)
param_cols = pd.concat([proj_dummies, comp_dummies, df[continuous_input_cols]], axis=1).columns.tolist()

num_params, num_output = len(param_cols), len(output_cols)

# 1.4 Normalization
p_min, p_max = X_raw.min(axis=0), X_raw.max(axis=0)
o_min, o_max = Y_raw.min(axis=0), Y_raw.max(axis=0)
p_range = np.where((p_max - p_min) == 0, 1.0, p_max - p_min)
o_range = np.where((o_max - o_min) == 0, 1.0, o_max - o_min)

idx = int(len(X_raw) * 0.8)
X_train_norm, X_valid_norm = jnp.array((X_raw[:idx] - p_min) / p_range), jnp.array((X_raw[idx:] - p_min) / p_range)
Y_train_norm, Y_valid_norm = jnp.array((Y_raw[:idx] - o_min) / o_range), jnp.array((Y_raw[idx:] - o_min) / o_range)

# --- 2. MODEL WITH NON-NEGATIVE OUTPUT ---
class ConstructionNN(nnx.Module):
    def __init__(self, rngs: nnx.Rngs):
        self.linear1 = nnx.Linear(num_params, 128, rngs=rngs)
        self.linear2 = nnx.Linear(128, 64, rngs=rngs)
        self.linear3 = nnx.Linear(64, num_output, rngs=rngs)
    def __call__(self, x):
        x = nnx.silu(self.linear1(x))
        x = nnx.silu(self.linear2(x))
        x = self.linear3(x)
        # Softplus prevents negative numbers while allowing high positive values
        return jax.nn.softplus(x)

model = ConstructionNN(rngs=nnx.Rngs(42))
optimizer = nnx.Optimizer(model, wrt=nnx.Param, tx=optax.adam(5e-4))

@nnx.jit
def train_step(mod, opt, X, Y):
    def loss_fn(m):
        preds = m(X)
        diff = preds - Y
        # Penalty for under-prediction (diff < 0 means actual > pred)
        penalty = jnp.where(diff < 0, 4.0, 1.0)
        return jnp.mean(penalty * (diff**2))
    grads = nnx.grad(loss_fn)(mod)
    opt.update(mod, grads)

# --- 3. TRAINING LOOP ---
log_epochs, log_loss_train, log_loss_valid = [], [], []
print(f"🚀 Training for Overrun Accuracy...")
for epoch in range(10001):
    train_step(model, optimizer, X_train_norm, Y_train_norm)
    if epoch % 500 == 0:
        l_t = float(jnp.mean((model(X_train_norm) - Y_train_norm)**2))
        l_v = float(jnp.mean((model(X_valid_norm) - Y_valid_norm)**2))
        log_epochs.append(epoch); log_loss_train.append(l_t); log_loss_valid.append(l_v)
        print(f'Epoch: {epoch:>5} | Train MSE: {l_t:.3e} | Valid MSE: {l_v:.3e}')

# --- 4. EXPORT ---
# Compatibility Fix: Export state as pure dictionary of numpy arrays
# This avoids 'AttributeError: _raw_value' in different environments
pure_state = jax.tree_util.tree_map(
    lambda x: np.array(x.value) if hasattr(x, 'value') else np.array(x),
    nnx.state(model, nnx.Param)
)

joblib.dump({
    'model_state': pure_state,
    'param_cols': param_cols,
    'params_min': p_min, 'params_range': p_range,
    'output_min': o_min, 'output_range': o_range,
    'type_risk_distribution': type_risk_dist.to_dict(),
    'avg_cost_weights': avg_cost_weights.values.tolist(),
    'avg_time_weights': avg_time_weights,
    'global_overrun_avg': float(global_overrun_avg),
    'encoded_project_cols': [c for c in param_cols if c.startswith('Proj_')],
    'encoded_complexity_cols': [c for c in param_cols if c.startswith('Comp_')]
}, 'project_model.pkl')

# Also save the training history for visualization
np.savez(
    'validation_results.npz',
    log_epochs=np.array(log_epochs),
    log_train=np.array(log_loss_train),
    log_valid=np.array(log_loss_valid),
    true=np.array(Y_raw[idx:]), # Save true values for plotting
    pred=np.array(model(X_valid_norm)) * o_range + o_min, # Save denormalized predictions
    labels=np.array(output_cols) # Save output column names
)

print("✅ Exported project_model.pkl and validation_results.npz")

import numpy as np
data = np.load('validation_results.npz')
print("Keys in file:", data.files)
print("Number of epochs saved:", len(data['log_epochs']))

import numpy as np
import matplotlib.pyplot as plt

# Load the data
try:
    data = np.load('validation_results.npz', allow_pickle=True)
    epochs = data['log_epochs']
    loss_train = data['log_train']
    loss_valid = data['log_valid']
    print("📈 Training history loaded.")
except Exception as e:
    print(f"❌ Error loading history: {e}")
else:
    # --- GRAPH: TRAINING HISTORY ---
    if len(epochs) > 0:
        plt.figure(figsize=(10, 5))
        plt.plot(epochs, loss_train, label='Training Loss', linewidth=2)
        plt.plot(epochs, loss_valid, label='Validation Loss', linestyle='--')

        plt.yscale('log') # Log scale helps see small changes at the end
        plt.title('Construction Analytics Model: Training History', fontsize=14, fontweight='bold')
        plt.xlabel('Epochs', fontsize=12)
        plt.ylabel('Mean Squared Error (Log Scale)', fontsize=12)
        plt.legend()
        plt.grid(True, which="both", alpha=0.3)
        plt.tight_layout()
        plt.show()
    else:
        print("No training history data found in the file.")

import numpy as np
import matplotlib.pyplot as plt

# Load the data
try:
    data = np.load('validation_results.npz', allow_pickle=True)
    Y_true = data['true']
    Y_pred = data['pred']
    labels = data['labels']
    print(f"📈 Prediction data loaded: {Y_true.shape[0]} validation samples.")
except Exception as e:
    print(f"❌ Error loading data: {e}")
else:
    # --- GRAPH: STAGE PARITY PLOTS ---
    fig, axs = plt.subplots(2, 5, figsize=(22, 10))
    axs = axs.flatten()

    for i in range(10):
        # Scatter plot of actual vs predicted
        axs[i].scatter(Y_true[:, i], Y_pred[:, i], s=3, alpha=0.3, color='#1f77b4')

        # Identity line (The "Perfect Prediction" red line)
        low = min(Y_true[:, i].min(), Y_pred[:, i].min())
        high = max(Y_true[:, i].max(), Y_pred[:, i].max())
        axs[i].plot([low, high], [low, high], '--', color='red', linewidth=1.5)

        # Labels and Grid
        axs[i].set_title(labels[i], fontsize=12, fontweight='bold')
        axs[i].set_xlabel('Actual Value', fontsize=9)
        axs[i].set_ylabel('Predicted Value', fontsize=9)
        axs[i].grid(True, alpha=0.2)

    plt.suptitle('Prediction Performance: Actual vs. Predicted (Per Stage)', fontsize=20, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

"""# Preview app"""

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import numpy as np
import matplotlib.pyplot as plt
import joblib
from flax import nnx
import jax.numpy as jnp
import jax

# --- 1. LOAD ASSETS ---
try:
    assets = joblib.load('project_model.pkl')

    class ConstructionNN(nnx.Module):
        def __init__(self, input_dim, output_dim, rngs):
            self.linear1 = nnx.Linear(input_dim, 128, rngs=rngs)
            self.linear2 = nnx.Linear(128, 64, rngs=rngs)
            self.linear3 = nnx.Linear(64, output_dim, rngs=rngs)
        def __call__(self, x):
            x = nnx.silu(self.linear1(x))
            x = nnx.silu(self.linear2(x))
            return jax.nn.softplus(self.linear3(x))

    model = ConstructionNN(len(assets['param_cols']), 10, nnx.Rngs(0))
    nnx.update(model, assets['model_state'])
    print("✅ Model Assets Loaded Successfully.")
except Exception as e:
    print(f"❌ Error loading 'project_model.pkl': {e}")

# --- 2. UI DESIGN ---
style = {'description_width': 'initial'}
proj_type = widgets.Dropdown(options=['Building', 'Power Plant', 'Road', 'Bridge', 'Water Infra'], description="Project Type:", style=style)
area_m2 = widgets.FloatText(value=5000.0, description="Area (m²):", style=style)
total_cost = widgets.FloatText(value=1000000.0, description="Target Budget ($):", style=style)
total_time = widgets.IntText(value=300, description="Target Total Days:", style=style)

complexity = widgets.SelectionSlider(options={'Low': 1, 'Medium': 2, 'High': 3}, description="Complexity:", style=style)
risk_score = widgets.IntSlider(value=50, min=0, max=100, description="Risk Score:", style=style)
res_score = widgets.IntSlider(value=50, min=0, max=100, description="Resource Score:", style=style)

stages_list = ["Site Prep", "Foundation", "Structure", "Systems", "Finishes"]
stage_checks = {s: widgets.Checkbox(description=s) for s in stages_list}
stage_data = {s: widgets.HBox([
    widgets.FloatText(placeholder="Actual $", description="Act $", layout={'width': '150px'}, style=style),
    widgets.IntText(placeholder="Actual Days", description="Act Days:", layout={'width': '150px'}, style=style)
], layout={'display': 'none'}) for s in stages_list}

def toggle_inputs(change):
    name = change['owner'].description
    stage_data[name].layout.display = 'flex' if change['new'] else 'none'
for cb in stage_checks.values(): cb.observe(toggle_inputs, names='value')

# --- 3. ANALYSIS ENGINE ---
btn = widgets.Button(description="📈 RUN PREDICTIVE ANALYSIS", button_style='success', layout={'width': '100%', 'height': '50px'})
out = widgets.Output()

def get_forecast():
    # 1. Encodings
    proj_vec = [0] * len(assets['encoded_project_cols'])
    try:
        proj_idx = assets['encoded_project_cols'].index(f"Proj_{proj_type.value}")
        proj_vec[proj_idx] = 1
    except: pass

    comp_vec = [0] * len(assets['encoded_complexity_cols'])
    c_map = {1: 'Comp_Low', 2: 'Comp_Medium', 3: 'Comp_High'}
    try:
        comp_idx = assets['encoded_complexity_cols'].index(c_map[complexity.value])
        comp_vec[comp_idx] = 1
    except: pass

    # 2. Engineered Features
    overrun_adj = assets.get('global_overrun_avg', 1.0)
    internal_names = ['Site_Prep_Actual_Cost', 'Foundations_Actual_Cost', 'Structure_Actual_Cost', 'Systems_Actual_Cost', 'Finishing_Actual_Cost']

    e_costs, e_risks = [], []
    for i in range(5):
        e_costs.append(total_cost.value * assets['avg_cost_weights'][i] * overrun_adj)
        risk_factor = assets['type_risk_distribution'][internal_names[i]].get(proj_type.value, 0.2)
        e_risks.append(risk_score.value * risk_factor)

    # 3. Assemble and Predict
    core_cont = [area_m2.value, res_score.value, total_time.value]
    full_input = proj_vec + comp_vec + core_cont + e_costs + e_risks
    feat = (np.array(full_input) - assets['params_min']) / assets['params_range']
    pred = model(jnp.array([feat]))[0]
    return np.array(pred) * assets['output_range'] + assets['output_min']

def run_analysis(b):
    with out:
        clear_output(wait=True)
        nn_out = get_forecast()
        pred_costs = np.maximum(0, nn_out[:5])
        pred_days = np.maximum(1, nn_out[5:])

        # Cumulative trackers
        pv_acc, d_acc_planned = 0, 0
        pv_curve, days_planned = [0], [0]

        # Table data
        rows = ""
        actual_count = 0

        # Calculate EVM components
        ev_total, ac_total = 0, 0

        # For plotting the Reality Line
        reality_days = [0]
        reality_costs = [0]
        cur_reality_day = 0
        cur_reality_cost = 0

        for i, s in enumerate(stages_list):
            # Planned Logic
            est_c = total_cost.value * assets['avg_cost_weights'][i]
            est_d = int(round(total_time.value * assets['avg_time_weights'][i]))
            pv_acc += est_c
            d_acc_planned += est_d
            pv_curve.append(pv_acc)
            days_planned.append(d_acc_planned)

            # Actual vs Forecast Logic
            if stage_checks[s].value:
                val_c = stage_data[s].children[0].value
                val_d = int(stage_data[s].children[1].value)
                ev_total += est_c
                ac_total += val_c
                status = "✅ Actual"
                actual_count += 1
            else:
                val_c = float(pred_costs[i])
                val_d = int(round(pred_days[i]))
                status = "🔮 Forecast"

            cur_reality_day += val_d
            cur_reality_cost += val_c
            reality_days.append(cur_reality_day)
            reality_costs.append(cur_reality_cost)

            rows += f"<tr><td>{s} ({status})</td><td>${est_c:,.0f}</td><td>{est_d}</td><td>${val_c:,.0f}</td><td>{val_d}</td></tr>"

        # Corrected Metrics
        eac = reality_costs[-1] # EAC is the end of the Predictive reality line
        cpi = ev_total / ac_total if ac_total > 0 else 1.0
        spi = ev_total / pv_acc if pv_acc > 0 else 1.0

        # --- PLOTTING ---
        plt.figure(figsize=(10, 5))
        # Baseline
        plt.plot(days_planned, pv_curve, 'b-o', label='Planned (Baseline)', alpha=0.3)
        # Actuals part of the line
        plt.plot(reality_days[:actual_count+1], reality_costs[:actual_count+1], 'r-x', label='Actual (Spend)', linewidth=2)
        # Predictive part
        plt.plot(reality_days[actual_count:], reality_costs[actual_count:], 'r--', label='AI Predictive Forecast')

        plt.title("Predictive Dashboard: Budget vs. AI Reality")
        plt.ylabel("Cumulative Cost ($)"); plt.xlabel("Days"); plt.legend(); plt.grid(True, alpha=0.2)
        plt.show()

        display(HTML(f"""<div style='border:1px solid #ddd; padding:15px; border-radius:10px; font-family:sans-serif; background:#222; color:white;'>
            <h3 style='text-align:center;'>Predictive EVM Analysis</h3>
            <p style='text-align:center;'><b>CPI:</b> {cpi:.2f} | <b>SPI:</b> {spi:.2f} | <b>Projected EAC:</b> ${eac:,.0f}</p>
            <table style='width:100%; border-collapse:collapse; color:white;'>
                <tr style='background:#444;'><th>Stage</th><th>Est. Budget</th><th>Est. Days</th><th>Act/Pred Cost</th><th>Act/Pred Days</th></tr>
                {rows}
            </table></div>"""))

btn.on_click(run_analysis)
display(widgets.VBox([
    widgets.HTML("<h2 style='color:#2e7d32; text-align:center;'>Predictive Project Control</h2>"),
    proj_type, area_m2, total_cost, total_time, complexity, risk_score, res_score,
    widgets.HTML("<hr><p><b>Update Stage Progress:</b></p>"),
    widgets.VBox([widgets.HBox([stage_checks[s], stage_data[s]]) for s in stages_list]),
    btn, out
]))

"""# 3. Streamlit Web Application"""

!pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# import plotly.graph_objects as go
# from flax import nnx
# import jax.numpy as jnp
# import jax # Add this line to import jax
# 
# # --- 1. MODEL RECONSTRUCTION ---
# # This must match your Training Script architecture exactly
# class ConstructionNN(nnx.Module):
#     def __init__(self, input_dim, output_dim, rngs):
#         # Changed hidden layer sizes and activation functions to match the training script
#         self.linear1 = nnx.Linear(input_dim, 128, rngs=rngs)
#         self.linear2 = nnx.Linear(128, 64, rngs=rngs)
#         self.linear3 = nnx.Linear(64, output_dim, rngs=rngs)
#     def __call__(self, x):
#         x = nnx.silu(self.linear1(x))
#         x = nnx.silu(self.linear2(x))
#         x = self.linear3(x)
#         # Softplus prevents negative numbers while allowing high positive values
#         return jax.nn.softplus(x)
# 
# @st.cache_resource
# def load_assets():
#     try:
#         assets = joblib.load("project_model.pkl")
#         # Initialize model structure with correct dimensions
#         model = ConstructionNN(len(assets['param_cols']), 10, nnx.Rngs(0)) # output_dim is 10 (5 costs, 5 days)
#         # Load the saved state
#         nnx.update(model, assets['model_state'])
#         return model, assets
#     except Exception as e:
#         st.error(f"Error loading assets: {e}")
#         return None, None
# 
# model, assets = load_assets()
# 
# # --- CONFIGURATION ---
# st.set_page_config(page_title="Predictive EVM Tool", layout="wide")
# st.title("🏗️ Predictive Earned Value Management")
# st.markdown("--- ---")
# 
# if assets:
#     # --- PART 1: PROJECT PARAMETERS ---
#     st.sidebar.header("1. Project Scope")
#     proj_type = st.sidebar.selectbox("Project Type", ['Building', 'Power Plant', 'Road', 'Bridge', 'Water Infra'])
#     area = st.sidebar.number_input("Engineered Area (m²)", min_value=1.0, value=5000.0)
#     est_cost = st.sidebar.number_input("Total Target Budget (€)", min_value=1000.0, value=1000000.0)
#     est_time = st.sidebar.number_input("Total Target Days", min_value=1, value=300)
# 
#     st.sidebar.markdown("--- ---")
#     st.sidebar.header("2. Risk & Complexity")
#     # Use a simpler map for complexity for input selection, then convert to one-hot
#     comp_label = st.sidebar.select_slider("Complexity", options=["Low", "Medium", "High"], value="Medium")
#     risk = st.sidebar.slider("Risk Assessment Score", 0, 100, 50)
#     res_score = st.sidebar.slider("Resource Allocation Score", 0, 100, 50)
# 
#     # --- PART 2: COMPLETION STATUS ---
#     st.header("Project Progress")
#     stages = ["Site Preparation", "Foundation", "Structures", "Systems", "Finishes"]
#     cols = st.columns(len(stages))
#     actual_data = {}
#     completed_stages_count = 0
# 
#     for i, stage in enumerate(stages):
#         with cols[i]:
#             st.subheader(stage)
#             is_done = st.checkbox("Done", key=f"done_{i}")
#             if is_done:
#                 completed_stages_count += 1
#                 act_c = st.number_input("Act. Cost (€)", key=f"c_{i}", min_value=0.0, value=0.0)
#                 act_t = st.number_input("Act. Days", key=f"t_{i}", min_value=0, step=1, value=0)
#                 actual_data[i] = {"cost": act_c, "time": int(act_t)}
# 
#     # --- PART 3: ANALYSIS ENGINE ---
#     if st.button("📈 RUN PREDICTIVE ANALYSIS", type="primary"):
#         # 1. Encodings for Project Type and Complexity (one-hot)
#         proj_vec = [0] * len(assets['encoded_project_cols'])
#         try:
#             proj_idx = assets['encoded_project_cols'].index(f"Proj_{proj_type}")
#             proj_vec[proj_idx] = 1
#         except ValueError: pass
# 
#         comp_vec = [0] * len(assets['encoded_complexity_cols'])
#         # Map comp_label string to numeric then to one-hot column name
#         complexity_map_for_onehot = {"Low": 1, "Medium": 2, "High": 3}
#         c_map_internal = {1: 'Comp_Low', 2: 'Comp_Medium', 3: 'Comp_High'}
#         complexity_numeric_val = complexity_map_for_onehot[comp_label]
#         try:
#             comp_idx = assets['encoded_complexity_cols'].index(c_map_internal[complexity_numeric_val])
#             comp_vec[comp_idx] = 1
#         except ValueError: pass
# 
#         # 2. Engineered Features (matching Preview App's logic)
#         overrun_adj = assets.get('global_overrun_avg', 1.0)
#         # These internal names are used to query type_risk_distribution from joblib assets
#         internal_output_names = ['Site_Prep_Actual_Cost', 'Foundations_Actual_Cost', 'Structure_Actual_Cost', 'Systems_Actual_Cost', 'Finishing_Actual_Cost']
# 
#         e_costs, e_risks = [], []
#         for i in range(5):
#             # est_cost here is the total project budget from sidebar
#             e_costs.append(est_cost * assets['avg_cost_weights'][i] * overrun_adj)
#             # type_risk_distribution holds average stage cost contribution per project type
#             risk_factor = assets['type_risk_distribution'].get(proj_type, {}).get(internal_output_names[i], 0.2)
#             e_risks.append(risk * risk_factor) # 'risk' is from the slider
# 
#         # 3. Assemble full input matching 'param_cols' order from training script
#         core_cont_inputs = [area, res_score, est_time]
#         full_input_list = proj_vec + comp_vec + core_cont_inputs + e_costs + e_risks
# 
#         # Normalize and predict
#         features = (np.array(full_input_list).astype(np.float32) - assets['params_min']) / assets['params_range']
#         prediction = model(jnp.array([features]))[0]
#         nn_res = np.array(prediction) * assets['output_range'] + assets['output_min']
# 
#         # Apply non-negative constraints to predictions
#         pred_costs = np.maximum(0, nn_res[:5])
#         pred_days = np.maximum(1, nn_res[5:]) # Ensure days are at least 1
# 
#         # --- EVM Calculation and Plotting Logic (matching Preview App) ---
#         pv_acc_total = 0 # Cumulative Planned Value for the entire project baseline
#         days_planned_cumulative = [0] # Cumulative planned days for baseline S-curve
#         pv_points = [0] # Cumulative planned cost for baseline S-curve
# 
#         ev_total = 0 # Earned Value for completed stages
#         ac_total = 0 # Actual Cost for completed stages
# 
#         reality_days_plot = [0] # Cumulative days for the reality line (actual + forecast)
#         reality_costs_plot = [0] # Cumulative costs for the reality line (actual + forecast)
# 
#         table_rows_data = [] # Data for the stage breakdown table
# 
#         for i, stage_name in enumerate(stages):
#             # Planned values for this stage
#             est_c_stage = est_cost * assets['avg_cost_weights'][i]
#             est_d_stage = int(round(est_time * assets['avg_time_weights'][i]))
# 
#             # Update total planned S-curve
#             pv_acc_total += est_c_stage
#             days_planned_cumulative.append(days_planned_cumulative[-1] + est_d_stage)
#             pv_points.append(pv_acc_total)
# 
#             current_stage_val_c = 0.0
#             current_stage_val_d = 0
#             status_type = ""
# 
#             if i in actual_data: # Stage is marked as 'Done' in the UI
#                 current_stage_val_c = actual_data[i]['cost']
#                 current_stage_val_d = actual_data[i]['time']
#                 ev_total += est_c_stage # EV is the planned cost of the work performed
#                 ac_total += current_stage_val_c # AC is the actual cost incurred
#                 status_type = "Actual"
#             else:
#                 current_stage_val_c = float(pred_costs[i])
#                 current_stage_val_d = int(round(pred_days[i]))
#                 status_type = "NN Prediction"
# 
#             # Update reality line
#             reality_days_plot.append(reality_days_plot[-1] + current_stage_val_d)
#             reality_costs_plot.append(reality_costs_plot[-1] + current_stage_val_c)
# 
#             table_rows_data.append({
#                 "Stage": stage_name,
#                 "Type": status_type,
#                 "Est. Cost (€)": f"{est_c_stage:,.0f}",
#                 "Est. Days": est_d_stage,
#                 "Actual/Pred Cost (€)": f"{current_stage_val_c:,.0f}",
#                 "Actual/Pred Days": current_stage_val_d
#             })
# 
#         # --- Corrected Metrics ---
#         eac_final_cost = reality_costs_plot[-1] # EAC is the end of the Predictive reality line
#         cpi = ev_total / ac_total if ac_total > 0 else 1.0
# 
#         # Calculate PV for completed stages specifically for SPI (as per Preview app's logic)
#         pv_completed_for_spi = 0
#         for k in range(completed_stages_count):
#              pv_completed_for_spi += est_cost * assets['avg_cost_weights'][k]
#         spi = ev_total / pv_completed_for_spi if pv_completed_for_spi > 0 else 1.0
# 
#         # --- PART 4: DISPLAY METRICS ---
#         k1, k2, k3 = st.columns(3)
#         k1.metric("CPI (Cost Efficiency)", f"{cpi:.2f}")
#         k2.metric("SPI (Schedule Efficiency)", f"{spi:.2f}")
#         k3.metric("EAC (Forecasted Total)", f"€{eac_final_cost:,.0f}")
# 
#         # --- Plotly S-Curve (matching Preview App visualization) ---
#         fig = go.Figure()
# 
#         # Planned Value (Baseline)
#         fig.add_trace(go.Scatter(x=days_planned_cumulative, y=pv_points, name="Planned Value (Baseline)", line=dict(color='blue', dash='dot')))
# 
#         # Actual Cost (red solid line for completed stages)
#         fig.add_trace(go.Scatter(x=reality_days_plot[:completed_stages_count+1], y=reality_costs_plot[:completed_stages_count+1],
#                                  name="Actual (Spend)", mode='lines+markers', line=dict(color='red', width=3)))
# 
#         # AI Predictive Forecast (red dashed line for remaining stages)
#         if completed_stages_count < len(stages):
#             fig.add_trace(go.Scatter(x=reality_days_plot[completed_stages_count:], y=reality_costs_plot[completed_stages_count:],
#                                      name="AI Predictive Forecast", line=dict(color='red', dash='dash', width=2)))
# 
#         # Earned Value (green line for completed stages)
#         # EV should track the PV of completed work
#         ev_plot_points = [0]
#         cumulative_planned_cost_for_ev_plot = 0
#         for k in range(completed_stages_count):
#              cumulative_planned_cost_for_ev_plot += est_cost * assets['avg_cost_weights'][k]
#         ev_plot_points.append(cumulative_planned_cost_for_ev_plot)
# 
#         # Days for EV plot should follow the actual_days for completed stages up to the status date
#         ev_days_plot = reality_days_plot[:completed_stages_count+1]
#         if len(ev_days_plot) > 0:
#             fig.add_trace(go.Scatter(x=ev_days_plot, y=ev_plot_points, name="Earned Value", mode='lines+markers', line=dict(color='green', width=3)))
# 
# 
#         fig.update_layout(title="Predictive EVM Analysis: Budget vs. AI Reality", xaxis_title="Days", yaxis_title="Cost (€)", height=500, width=700)
#         st.plotly_chart(fig, width='stretch') # Changed use_container_width=True to width='stretch'
# 
#         # --- Stage Breakdown Table ---
#         st.markdown("--- ---")
#         st.subheader("Stage-wise Breakdown")
#         st.table(pd.DataFrame(table_rows_data))
# else:
#     st.warning("Awaiting Model Assets. Please ensure 'project_model.pkl' exists and is loaded successfully.")

!streamlit run app.py & npx localtunnel --port 8501

!npm install -g localtunnel
!streamlit run app.py & npx localtunnel --port 8501

pip install pyngrok -q

from pyngrok import ngrok

# Terminate any previous ngrok tunnels
ngrok.kill()

# Authenticate ngrok. You might be prompted to get an authtoken from ngrok.com.
# If you've already authenticated in a previous session, this might not be strictly necessary.
# ngrok.set_auth_token("YOUR_NGROK_AUTH_TOKEN") # Uncomment and replace if you have an authtoken

# Start Streamlit in the background
!streamlit run app.py &

# Create a public URL for Streamlit
public_url = ngrok.connect(8501)
print(f"Streamlit App URL: {public_url}")

"""# Image"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

def draw_tech_dashboard():
    # --- 1. SETUP CANVAS ---
    fig, ax = plt.subplots(figsize=(16, 9), dpi=100)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.axis('off')

    # Background Colors
    BG_DARK = '#0a0e14'
    PANEL_BLUE = '#141c26'
    ACCENT_TEAL = '#00d4ff'
    ACCENT_GOLD = '#ffcc00'
    ACCENT_RED = '#ff4b4b'
    SUCCESS_GREEN = '#4CAF50'

    fig.patch.set_facecolor(BG_DARK)
    ax.set_facecolor(BG_DARK)

    # --- 2. THE PROCESSOR (CENTER BRAIN) ---
    brain_circle = patches.Circle((50, 65), 12, facecolor='#1a2a3a', edgecolor=ACCENT_TEAL, linewidth=3, zorder=3)
    ax.add_patch(brain_circle)
    ax.text(50, 68, "NEURAL NETWORK\nPROCESSOR", color='white', weight='bold', fontsize=14, ha='center')
    ax.text(50, 60, "(MLP Regressor)", color=ACCENT_TEAL, fontsize=10, ha='center')

    # Abstract connections/nodes inside brain
    for _ in range(12):
        x, y = np.random.uniform(42, 58), np.random.uniform(58, 72)
        ax.scatter(x, y, s=20, color=ACCENT_GOLD, alpha=0.6, zorder=4)

    # --- 3. LEFT PANEL: INPUTS ---
    # Mandatory Inputs
    ax.add_patch(patches.Rectangle((5, 55), 30, 35, facecolor=PANEL_BLUE, edgecolor=ACCENT_TEAL, alpha=0.3, lw=1))
    ax.text(7, 87, "MANDATORY INPUTS", color='white', weight='bold', fontsize=12)

    inputs = ["Project Type", "Area (m²)", "Complexity", "Est. Cost ($)", "Est. Time (Days)"]
    for i, label in enumerate(inputs):
        y_pos = 81 - (i * 5.5)
        ax.text(8, y_pos, f"▣ {label}", color='white', alpha=0.8, fontsize=10)
        ax.arrow(35, y_pos, 8, 0, head_width=1, head_length=1.5, fc=ACCENT_TEAL, ec=ACCENT_TEAL, alpha=0.4)

    # Monitoring Inputs
    ax.add_patch(patches.Rectangle((5, 15), 30, 30, facecolor=PANEL_BLUE, edgecolor=ACCENT_GOLD, alpha=0.3, lw=1))
    ax.text(7, 41, "LIVE MONITORING", color=ACCENT_GOLD, weight='bold', fontsize=12)
    ax.text(8, 35, "Current Stage Select ▼", color='white', fontsize=10)
    ax.text(8, 28, "Actual Cost (AC)", color='white', fontsize=10)
    ax.text(8, 21, "Actual Time (AD)", color='white', fontsize=10)

    # --- 4. CENTER LOWER: GAUGES ---
    def draw_mini_gauge(x, y, val, label, color):
        ax.add_patch(patches.Wedge((x, y), 6, 0, 180, width=2, facecolor='#222', zorder=1))
        ax.add_patch(patches.Wedge((x, y), 6, 180-(val*180), 180, width=2, facecolor=color, zorder=2))
        ax.text(x, y-3, label, color='white', fontsize=10, ha='center', weight='bold')
        ax.text(x, y+1, f"{val:.2f}", color='white', fontsize=12, ha='center', weight='bold')

    draw_mini_gauge(40, 30, 0.85, "STAGE CPI", ACCENT_GOLD)
    draw_mini_gauge(60, 30, 0.92, "STAGE SPI", ACCENT_TEAL)

    # Correction Factor Arrow
    ax.annotate("CORRECTION FACTOR\n(Updates Future Stages)", xy=(80, 25), xytext=(50, 15),
                arrowprops=dict(arrowstyle="->", color=ACCENT_RED, lw=3, connectionstyle="arc3,rad=-0.2"),
                color=ACCENT_RED, weight='bold', ha='center')

    # --- 5. RIGHT PANEL: OUTPUTS ---
    # Cost Forecast Panel
    ax.add_patch(patches.Rectangle((65, 55), 30, 35, facecolor=PANEL_BLUE, edgecolor=ACCENT_TEAL, alpha=0.5, lw=1))
    ax.text(67, 87, "COST FORECAST", color='white', weight='bold', fontsize=12)

    # Data for the pie chart
    forecast_costs_data = [
        ("Site_Prep", 1.2),
        ("Foundations", 1.8),
        ("Structure", 2.5),
        ("Systems", 1.5),
        ("Finishing", 0.8)
    ]
    labels = [f"{stage}: ${cost:.1f}M" for stage, cost in forecast_costs_data]
    sizes = [cost for stage, cost in forecast_costs_data]
    colors = [ACCENT_GOLD, ACCENT_TEAL, ACCENT_GOLD, ACCENT_TEAL, ACCENT_GOLD] # Using the same accent colors

    # Draw the pie chart
    wedge_sizes = [s / sum(sizes) for s in sizes]
    cumulative_angles = np.cumsum([0] + [s * 360 for s in wedge_sizes])

    for i, size in enumerate(wedge_sizes):
        start_angle = cumulative_angles[i]
        end_angle = cumulative_angles[i+1]
        # Adjust radius and center for placement in the panel
        pie_wedge = patches.Wedge(center=(80, 70), r=10, theta1=start_angle, theta2=end_angle, facecolor=colors[i], edgecolor='white', linewidth=1)
        ax.add_patch(pie_wedge)

        # Add labels to the pie chart
        mid_angle = (start_angle + end_angle) / 2
        x_text = 80 + 12 * np.cos(np.deg2rad(mid_angle))
        y_text = 70 + 12 * np.sin(np.deg2rad(mid_angle))
        ax.text(x_text, y_text, labels[i], color='white', ha='center', va='center', fontsize=8)

    total_forecast = sum(sizes)
    ax.text(67, 50, f"Total Forecast: ${total_forecast:.1f}M", color=SUCCESS_GREEN, weight='bold', fontsize=11)
    ax.text(67, 46, "Completion: 320 Days", color='white', fontsize=10)


    # Final plot adjustments
    plt.tight_layout()
    plt.show()

# Call the function to draw the dashboard
draw_tech_dashboard()

import matplotlib.pyplot as plt
import numpy as np

# Set up the figure
plt.figure(figsize=(14, 8))
plt.style.use('seaborn-v0_8-whitegrid')

# --- 1. DATA DEFINITION ---
# Project is now 5 Stages long
# PV (Planned) ends at Stage 4 (Planned Finish)
# EAC (Actual/Est) ends at Stage 5 (Actual Finish)

# Planned Path (Ends at Stage 4)
planned_time = [0, 1, 2, 3, 4]
planned_val = [0, 100, 200, 300, 300] # Levels off at BAC

# PV (Planned Value) - Now a diagonal straight line from 0 to Stage 5
# To maintain a BAC of 300 at Stage 5:
planned_time = [0, 4.8]
planned_val = [0, 340]

# Actual Path (Solid line up to Stage 1)
time_now = 1
ac_now = 150
ac_x_solid = [0, time_now]
ac_y_solid = [0, ac_now]

# EAC Path (Dashed curve starting at Stage 1, ending at Stage 5)
# Formula adjusted to connect at (1, 150) and hit 350 at Stage 5
ac_x_dashed = np.linspace(time_now, 5, 100)
ac_y_dashed = -12.5 * (ac_x_dashed - 5)**2 + 350

# Earned Value (Up to current progress)
ev_x = [0, time_now]
ev_y = [0, 50]

# --- 2. PLOTTING ---
# Planned Value (PV)
plt.plot(planned_time, planned_val, color='cornflowerblue', label='PV', linewidth=2.5)

# Actual Cost (AC) & Estimate at Completion (EAC)
plt.plot(ac_x_solid, ac_y_solid, color='red', linewidth=3)
plt.plot(ac_x_dashed, ac_y_dashed, color='red', linestyle='--', linewidth=2.5)

# Earned Value (EV)
plt.plot(ev_x, ev_y, color='green', linewidth=3)

# --- 3. STAGE FINISH MARKERS ---
# Planned Finish at Stage 4
plt.axvline(x=4.8, color='blue', linestyle='--', alpha=0.5)
plt.text(4.8, -35, 'PLANNED\nFINISH', ha='center', color='blue', fontweight='bold', fontsize=10)

# Actual/Estimated Finish at Stage 5
plt.axvline(x=5, color='red', linestyle='--', alpha=0.5)
plt.text(5, -35, 'ACTUAL\nFINISH', ha='center', color='red', fontweight='bold', fontsize=10)

# Status Date - NOW A DOTTED BLACK LINE
plt.axvline(x=time_now, color='black', linestyle=':', linewidth=2)
plt.text(time_now, 380, 'Status Date', ha='center', color='black', fontweight='bold',
         bbox=dict(facecolor='white', edgecolor='none', alpha=0.7))

# --- 4. ANNOTATIONS ---
plt.text(1.1, 50, 'EV', color='green', fontsize=12, fontweight='bold')
plt.text(1.1, 115, 'PV', color='cornflowerblue', fontsize=12, fontweight='bold')
plt.text(0.7, 135, 'AC', color='red', fontsize=12, fontweight='bold')
plt.text(4.5, 355, 'EAC', color='red', fontsize=13, fontweight='bold')

# Horizontal budget lines
plt.axhline(y=340, color='cornflowerblue', linestyle=':', alpha=0.4)
plt.axhline(y=350, color='red', linestyle=':', alpha=0.4)

# --- 5. AXIS & STYLING ---
plt.title('EVM Graph: 5-Stage Completion Analysis', fontsize=16, pad=30)
plt.xlabel('Project Stages', loc='right', fontsize=12, labelpad=15)
plt.ylabel('Cost (€)', loc='top', fontsize=12)

# X-axis for 5 stages
plt.xticks(range(6), ['Start', 'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4', 'Stage 5'])
plt.yticks([0, 50, 100, 150, 200, 250, 300, 350])

plt.xlim(0, 5.5)
plt.ylim(0, 420)

# Clean aesthetics
ax = plt.gca()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(True, linestyle=':', alpha=0.5)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

def draw_ann_paper_style(
    layer_sizes,
    input_labels=None,
    output_labels=None,
    hidden_labels=None,
    title=None,
    figsize=(10, 12),
    node_size=20,
    line_width=0.35,
    line_grey="0.80"
):

    n_layers = len(layer_sizes)
    max_nodes = max(layer_sizes)

    fig, ax = plt.subplots(figsize=figsize)
    ax.axis("off")

    node_positions = []

    for li, n_nodes in enumerate(layer_sizes):
        slots = [1 - i / (max_nodes - 1) for i in range(max_nodes)] if max_nodes > 1 else [0.5]

        if n_nodes == 1:
            ys = [0.5]
        else:
            start = (max_nodes - n_nodes) // 2
            ys = slots[start:start + n_nodes]

        xs = [li] * n_nodes
        node_positions.append(list(zip(xs, ys)))

    for li in range(n_layers - 1):
        for (x1, y1) in node_positions[li]:
            for (x2, y2) in node_positions[li + 1]:
                ax.plot([x1, x2], [y1, y2], color=line_grey, linewidth=line_width, zorder=1)

    for li in range(n_layers):
        xs = [p[0] for p in node_positions[li]]
        ys = [p[1] for p in node_positions[li]]
        ax.scatter(xs, ys, s=node_size, color="black", zorder=2)

    if input_labels:
        for i, lbl in enumerate(input_labels):
            ax.text(-0.25, node_positions[0][i][1], lbl, ha="right", va="center", fontsize=11)
        ax.text(-0.25, 1.04, f"Input ({layer_sizes[0]})", ha="right", va="bottom", fontsize=11, style="italic")

    if output_labels:
        for i, lbl in enumerate(output_labels):
            ax.text(n_layers - 1 + 0.18, node_positions[-1][i][1], lbl, ha="left", va="center", fontsize=11)
        ax.text(n_layers - 1 + 0.18, 1.04, f"Output ({layer_sizes[-1]})", ha="left", va="bottom", fontsize=11, style="italic")

    if hidden_labels:
        hidden_layer_indices = list(range(1, n_layers - 1))
        for txt, li in zip(hidden_labels, hidden_layer_indices):
            ax.text(li, 1.04, txt, ha="center", va="bottom", fontsize=11, style="italic")

    if title:
        ax.set_title(title, fontsize=13, pad=16)

    ax.set_xlim(-0.6, n_layers - 0.4)
    ax.set_ylim(-0.05, 1.10)

    plt.show()



draw_ann_paper_style(
    layer_sizes=[8, 20, 20, 2],
    input_labels=["Project Type", "Area", "Estimated Cost", "Estimated Time", "Complexity", "Risk Score" , "Resource Score", "Stage progress"],
    output_labels=["Predicted Cost", "Predicted Time"],
    hidden_labels=["(20)", "(20)"],
    title=None,
    figsize=(10, 13),
    node_size=50,
    line_width=0.50,
    line_grey="0.82"
)